//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int ID { get; set; }
        public int FlatID { get; set; }
        public int BookingId { get; set; }
        public int Rent { get; set; }
    
        public virtual BookingDetail BookingDetails1 { get; set; }
        public virtual BookingDetail BookingDetail1 { get; set; }
    }
}
